### PR TITLE
Image Frame Interval Changer

### PR DESCRIPTION
**Pull request by aliL2000**
Adding BE functionality to add a new field so that the FE can send a HTTP request with a new field called "**interval**", where an integer must be sent to the BE 

@yuqi88  and @Jeena01 , please take a look at this, this is important

### CODE REVIEW

**Comment by aliL2000** [comment]
image

**Review by yuqi88 — APPROVED** [review]
LGTM

**Review by Jeena01 — APPROVED** [review]
LGTM!

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Pull request merged**
