### PR TITLE
Loading bar

### PR DESCRIPTION
**Pull request by Jeena01**
using useInterval for this

### CODE REVIEW

**Comment by Jeena01** [comment]
do not merge

**Comment by Jeena01** [comment]
yet

**Comment by Jeena01** [comment]
complete

**Comment by Jeena01** [comment]
theoretically

**Comment by Jeena01** [comment]
video upload issues

**Comment by Jeena01** [comment]
complete

**Review by aliL2000 — APPROVED** [review]
lgtm

**Pull request merged**
