### PR TITLE
Adding timestamps with each frame

### PR DESCRIPTION
**Pull request by aliL2000**
PR that adds timestamp to each image returned by DeepImageSearch

### CODE REVIEW

**Comment by aliL2000** [comment]
Screen Shot 2023-04-04 at 12 51 06 PM

Here is what the BE now sends to the FE, please take a look at this @yuqi88 and @Jeena01

**Review by yuqi88 — APPROVED** [review]
Thanks. LGTM

**Comment by yuqi88** [comment]
@aliL2000 everyone needs to run migrations after merging this pr right?

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by aliL2000** [comment]
This PR has some major changes as well, so please feel free to ask me any quesitons related to it

**Comment by aliL2000** [comment]
Also, please wipe your docker container and re-run the install to see if it all works

**Pull request merged**
