### PR TITLE
Team meeting notes

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Quick notes addition

### CODE REVIEW

**Review by Jeena01 — APPROVED** [review]
LGTM

**Review by aliL2000 — APPROVED** [review]
Nice job on the PR

**Comment by Brenden-Trieu** [comment]
Notes are to be deleted when handing off

**Comment by Brenden-Trieu** [comment]
The PR took a total of 2mins

**Comment by Brenden-Trieu** [comment]
worth it

**Pull request merged**
