### PR TITLE
Image gallery component

### PR DESCRIPTION
**Pull request by Jeena01**
added the component

### CODE REVIEW

**Comment by Jeena01** [comment]
good to merge i think

**Review by aliL2000 — APPROVED** [review]
Changes look good to me!

**Comment by aliL2000** [comment]
Close #35

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by Brenden-Trieu** [comment]
For future reference, we should include images of code working

**Review by yuqi88 — COMMENTED** [review]
LGTM

**Pull request merged**
