### PR TITLE
Update 1.tsx

### PR DESCRIPTION
**Pull request by Jeena01**
DO NOT MERGE YET

### CODE REVIEW

**Comment by Jeena01** [comment]
added an interval input box

**Comment by Jeena01** [comment]
haven't tested it though

**Comment by Jeena01** [comment]
Good to merge now

**Comment by Jeena01** [comment]
@Brenden-Trieu @aliL2000 @yuqi88

**Review by aliL2000 — APPROVED** [review]
Changes look good to me!

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by yuqi88** [comment]
LGTM

**Comment by yuqi88** [comment]
I'll delete the branch now for the cleanness of the branch control. Please pull from main when you are finishing the rest

**Pull request merged**
