### PR TITLE
Deep image search be integration

### PR DESCRIPTION
**Pull request by aliL2000**
PR changes BE functionality completely, and now we have an API that uploads deepImageSearch

### CODE REVIEW

**Review by yuqi88 — APPROVED** [review]
I'm so happy that backend docker works. LGTM

**Review by Brenden-Trieu — APPROVED** [review]
I was there

**Comment by Jeena01** [comment]
lgtm

**Comment by Brenden-Trieu** [comment]
Close #95

**Comment by Brenden-Trieu** [comment]
Close #108

**Comment by Brenden-Trieu** [comment]
Close #109

**Comment by Brenden-Trieu** [comment]
Close #110

**Comment by Brenden-Trieu** [comment]
Close #111

**Comment by aliL2000** [comment]
The changes look good to me! This pr re-structures the be and adds functionality for the be

**Pull request merged**
