### PR TITLE
API that wipes the DB

### PR DESCRIPTION
**Pull request by aliL2000**
An api that the FE can call that will wipe the db and clear all local files

### CODE REVIEW

**Comment by aliL2000** [comment]
image

**Comment by aliL2000** [comment]
@Jeena01  and @yuqi88 , please take a look at this PR, this is an API that deletes the db models, and the local files on systems.

**Review by yuqi88 — APPROVED** [review]
Lgtm

**Review by Brenden-Trieu — APPROVED** [review]
very nice good sir

**Comment by Jeena01** [comment]
LGTM

**Pull request merged**
