### PR TITLE
Add components

### PR DESCRIPTION
**Pull request by Jeena01**
PLEASE DO NOT MERGE

### CODE REVIEW

**Comment by Jeena01** [comment]
OK TO MERGE

**Comment by Jeena01** [comment]
temporary fix to stepper issue

**Review by aliL2000 — APPROVED** [review]
Looks good to me!

**Review by yuqi88 — APPROVED** [review]
LGTM

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by Brenden-Trieu** [comment]
Close #53

**Pull request merged**
