### PR TITLE
Label bar fix

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
label bar fixed and commented out for potential future functionality

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
closes #181

**Comment by Brenden-Trieu** [comment]
the current data being sent is still including the label, do we want to remove that or leave it?

the current PR makes the label changeable and then removes the alteration bar

**Review by yuqi88 — APPROVED** [review]
LGTM

**Comment by yuqi88** [comment]
We can leave the label in the request, but we could make this an issue. This feels like a clean-up task.

**Comment by yuqi88** [comment]
issue added #205

**Pull request merged**
