### PR TITLE
Image frame fixing

### PR DESCRIPTION
**Pull request by aliL2000**
Hold off on merging, still working on some fixes

### CODE REVIEW

**Comment by aliL2000** [comment]
PR is ready to be merged, but wait for next week

**Comment by Brenden-Trieu** [comment]
Will approve after re-running built tests (actions were updated to better test build)

**Comment by Brenden-Trieu** [comment]
Close #60

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by Jeena01** [comment]
LGTM

**Review by Jeena01 — APPROVED** [review]
LGTM!

**Pull request merged**
