### PR TITLE
Update settings.py

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
I added a definition for memory size in settings

Should fix the docker backend container problem

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
Close #129

**Review by Jeena01 — APPROVED** [review]
lgtm

**Comment by Jeena01** [comment]
thank you

**Review by yuqi88 — APPROVED** [review]
Thank you

**Comment by aliL2000** [comment]
Changes look good to me!

**Pull request merged**
