### PR TITLE
live reload still needs to be refreshed

### PR DESCRIPTION
**Pull request by Brenden-Trieu**
Docker live reloads backend and frontend

Frontend needs to refresh but still works

### CODE REVIEW

**Comment by Brenden-Trieu** [comment]
Close #68

**Review by Jeena01 — APPROVED** [review]
Lgtm!

**Comment by Jeena01** [comment]
Thank you

**Review by aliL2000 — APPROVED** [review]
lgtm

**Review by yuqi88 — APPROVED** [review]
LGTM

**Pull request merged**
