### PR TITLE
Vid upload frontend

### PR DESCRIPTION
**Pull request by Jeena01**
step 1 page separated

### CODE REVIEW

**Comment by Jeena01** [comment]
uncommented some stuff

**Comment by Jeena01** [comment]
dont merge yet

**Comment by Jeena01** [comment]
closes #73

**Comment by Jeena01** [comment]
complete

**Comment by Jeena01** [comment]
good to merge from my end

**Review by aliL2000 — APPROVED** [review]
Changes look good to me!

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by yuqi88** [comment]
LGTM

**Pull request merged**
