### PR TITLE
Adding BE from old repo to new repo

### PR DESCRIPTION
**Pull request by aliL2000**
This PR merges the BE from our old repo to the new repo, it also has the new video upload functionality.

### CODE REVIEW

**Comment by aliL2000** [comment]
Close #10 and #11

**Review by Brenden-Trieu — APPROVED** [review]
LGTM

**Comment by Jeena01** [comment]
LGTM

**Comment by Brenden-Trieu** [comment]
Wiping old branch with cookie cutter Django

**Pull request merged**
